### ISSUE TITLE
JP-1 - Move price change to station level

### ISSUE THREAD

**Issue by gamissah** [dklogoPJ/warpd_jp#2]
The current price change is at the OMC level. Where the OMC sets the price changes for all it stations. 

1. We need to move the price change module to the station level so each station can have it own price
2. Disable the price change module header at the OMC
3. Disable price change module for OMC

**Comment by dklogo** [comment]
Great, I think i will enter all the issues and the update here so we can monitor it

**Comment by gamissah** [comment]
Task Completed
